### ISSUE TITLE
Future RFE: Implement test scenario(s) for offline attestation

### ISSUE THREAD

**Issue by kkaarreell** [RedHat-SP-Security/keylime-tests#195]
We should have some functional test for
https://github.com/keylime/enhancements/blob/master/73-offline-attestation.md

**Comment by Koncpa** [comment]
https://github.com/keylime/keylime/pull/1097

**Comment by kkaarreell** [comment]
Related PR https://github.com/keylime/keylime/pull/1258

**Comment by kkaarreell** [comment]
Basic tests implemented in
https://github.com/RedHat-SP-Security/keylime-tests/pull/325
https://github.com/RedHat-SP-Security/keylime-tests/pull/336
